# Generated by Django 4.2.3 on 2023-07-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('student_number', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('program', models.CharField(max_length=100)),
                ('course_unit', models.CharField(max_length=100)),
                ('course_code', models.CharField(max_length=100)),
                ('course_instructor', models.CharField(max_length=100)),
                ('argument', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('student_number', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('program', models.CharField(max_length=100)),
                ('facility', models.CharField(max_length=100)),
                ('waden', models.CharField(max_length=100)),
                ('argument', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Instructors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('student_number', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('program', models.CharField(max_length=100)),
                ('course_unit', models.CharField(max_length=100)),
                ('course_code', models.CharField(max_length=100)),
                ('course_instructor', models.CharField(max_length=100)),
                ('argument', models.CharField(max_length=500)),
            ],
        ),
    ]
