# Generated by Django 4.2.4 on 2023-08-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mak_feedback', '0002_instructors_five_instructors_four_instructors_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilities',
            name='five',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facilities',
            name='four',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facilities',
            name='one',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facilities',
            name='third',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facilities',
            name='two',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
