# Generated by Django 4.2.3 on 2023-08-08 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mak_feedback', '0004_rename_five_instructors_learning_environment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facilities',
            old_name='five',
            new_name='awareness',
        ),
        migrations.RenameField(
            model_name='facilities',
            old_name='four',
            new_name='cleaning',
        ),
        migrations.RenameField(
            model_name='facilities',
            old_name='one',
            new_name='facilityQuery',
        ),
        migrations.RenameField(
            model_name='facilities',
            old_name='third',
            new_name='facilityUsage',
        ),
        migrations.RenameField(
            model_name='facilities',
            old_name='two',
            new_name='rating',
        ),
    ]
